name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libcurl
      run: sudo apt-get update && sudo apt-get -y install p7zip-full libc6-dev libcurl4-openssl-dev pkg-config autoconf libssl-dev libdeflate-dev
    - name: Install deps
      run: wget https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2 && tar -xjvf htslib-1.17.tar.bz2 && pushd htslib-1.17/ && autoreconf -i && ./configure && sudo make && sudo make install && popd 

    - name: configure
      run: autoreconf -iv && ./configure --with-libdeflate
    - name: make
      run:  make
    - name: Package
      run: 7z a Linux.zip *
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: target/Linux.zip
