name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: wget https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2 && tar -xzvf htslib-1.17.tar.bz2 && cd htslib-1.17/ && autoreconf -i && ./configure && make && make install && sudo apt-get update && sudo apt-get -y install p7zip-full libc6-dev libcurl4-openssl-dev
    - name: configure
      run: ./configure LDFLAGS="-static -fPIC"
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Package
      run: 7z a Linux.zip *
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: target/Linux.zip
